CREATE TABLE "app_label"
(
    "id"   bigint      NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "name" varchar(32) NOT NULL UNIQUE
);
CREATE TABLE "app_profile"
(
    "id"      bigint       NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "avatar"  varchar(100) NULL,
    "user_id" integer      NOT NULL UNIQUE
);
CREATE TABLE "app_question"
(
    "id"         bigint                   NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "title"      varchar(256)             NOT NULL,
    "text"       text                     NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "rating"     integer                  NOT NULL,
    "profile_id" bigint                   NULL
);
CREATE TABLE "app_question_labels"
(
    "id"          bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "question_id" bigint NOT NULL,
    "label_id"    bigint NOT NULL
);
CREATE TABLE "app_answer"
(
    "id"          bigint                   NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "text"        text                     NOT NULL,
    "correct"     boolean                  NOT NULL,
    "created_at"  timestamp with time zone NOT NULL,
    "rating"      integer                  NOT NULL,
    "profile_id"  bigint                   NULL,
    "question_id" bigint                   NOT NULL
);
CREATE TABLE "app_questionscore"
(
    "id"          bigint                   NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "value"       smallint                 NOT NULL,
    "created_at"  timestamp with time zone NOT NULL,
    "profile_id"  bigint                   NOT NULL,
    "question_id" bigint                   NOT NULL
);
CREATE TABLE "app_answerscore"
(
    "id"         bigint                   NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "value"      smallint                 NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "answer_id"  bigint                   NOT NULL,
    "profile_id" bigint                   NOT NULL
);
CREATE INDEX "app_label_name_fb46806c_like" ON "app_label" ("name" varchar_pattern_ops);
ALTER TABLE "app_profile"
    ADD CONSTRAINT "app_profile_user_id_87d292a0_fk_auth_user_id"
        FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_question"
    ADD CONSTRAINT "app_question_profile_id_36cf8c66_fk_app_profile_id"
        FOREIGN KEY ("profile_id") REFERENCES "app_profile" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_question_profile_id_36cf8c66" ON "app_question" ("profile_id");
ALTER TABLE "app_question_labels"
    ADD CONSTRAINT "app_question_labels_question_id_label_id_30e6eca1_uniq"
        UNIQUE ("question_id", "label_id");
ALTER TABLE "app_question_labels"
    ADD CONSTRAINT "app_question_labels_question_id_53344975_fk_app_question_id"
        FOREIGN KEY ("question_id") REFERENCES "app_question" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_question_labels"
    ADD CONSTRAINT "app_question_labels_label_id_b396fb08_fk_app_label_id"
        FOREIGN KEY ("label_id") REFERENCES "app_label" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_question_labels_question_id_53344975" ON "app_question_labels" ("question_id");
CREATE INDEX "app_question_labels_label_id_b396fb08" ON "app_question_labels" ("label_id");
ALTER TABLE "app_answer"
    ADD CONSTRAINT "app_answer_profile_id_140de116_fk_app_profile_id"
        FOREIGN KEY ("profile_id") REFERENCES "app_profile" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_answer"
    ADD CONSTRAINT "app_answer_question_id_4b805cab_fk_app_question_id"
        FOREIGN KEY ("question_id") REFERENCES "app_question" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_answer_profile_id_140de116" ON "app_answer" ("profile_id");
CREATE INDEX "app_answer_question_id_4b805cab" ON "app_answer" ("question_id");
ALTER TABLE "app_questionscore"
    ADD CONSTRAINT "app_questionscore_profile_id_question_id_be635b27_uniq"
        UNIQUE ("profile_id", "question_id");
ALTER TABLE "app_questionscore"
    ADD CONSTRAINT "app_questionscore_profile_id_a6e7b0a9_fk_app_profile_id"
        FOREIGN KEY ("profile_id") REFERENCES "app_profile" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_questionscore"
    ADD CONSTRAINT "app_questionscore_question_id_a82a70e4_fk_app_question_id"
        FOREIGN KEY ("question_id") REFERENCES "app_question" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_questionscore_profile_id_a6e7b0a9" ON "app_questionscore" ("profile_id");
CREATE INDEX "app_questionscore_question_id_a82a70e4" ON "app_questionscore" ("question_id");
ALTER TABLE "app_answerscore"
    ADD CONSTRAINT "app_answerscore_profile_id_answer_id_7f7d6326_uniq"
        UNIQUE ("profile_id", "answer_id");
ALTER TABLE "app_answerscore"
    ADD CONSTRAINT "app_answerscore_answer_id_85986bea_fk_app_answer_id"
        FOREIGN KEY ("answer_id") REFERENCES "app_answer" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "app_answerscore"
    ADD CONSTRAINT "app_answerscore_profile_id_b0b591fc_fk_app_profile_id"
        FOREIGN KEY ("profile_id") REFERENCES "app_profile" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "app_answerscore_answer_id_85986bea" ON "app_answerscore" ("answer_id");
CREATE INDEX "app_answerscore_profile_id_b0b591fc" ON "app_answerscore" ("profile_id");
