# Generated by Django 4.1.3 on 2023-06-05 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Label name')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='/avatar/default_avatar.jpeg', null=True, upload_to='avatar/%Y/%m/%d/', verbose_name='Profile avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Question title')),
                ('text', models.TextField(verbose_name='Question text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Question created time')),
                ('rating', models.IntegerField(default=0)),
                ('labels', models.ManyToManyField(blank=True, related_name='question', to='app.label')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question', to='app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Answer text')),
                ('correct', models.BooleanField(default=False, verbose_name='Answer correct')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Answer created time')),
                ('rating', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer', to='app.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='app.question')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.SmallIntegerField(choices=[(1, 'Positive'), (-1, 'Negative')], verbose_name='Score')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='app.profile', verbose_name='Profile')),
            ],
            options={
                'unique_together': {('profile', 'content_type', 'object_id')},
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='app_questio_created_eedfc6_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['rating'], name='app_questio_rating_ef1c4c_idx'),
        ),
    ]
