# Generated by Django 4.1.3 on 2023-06-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['created_at'], name='app_answer_created_9a6840_idx'),
        ),
    ]
