# Generated by Django 4.1.3 on 2023-06-06 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_answer_app_answer_created_9a6840_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answer',
            name='app_answer_created_9a6840_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='app_questio_created_eedfc6_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='app_questio_rating_ef1c4c_idx',
        ),
    ]
