# Generated by Django 4.1.3 on 2023-06-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_answer_app_answer_created_9a6840_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['created_at'], name='app_answer_created_9a6840_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='app_questio_created_eedfc6_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['rating'], name='app_questio_rating_ef1c4c_idx'),
        ),
    ]
