# Generated by Django 4.1.3 on 2023-06-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_answer_app_answer_created_9a6840_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
    ]
