# Generated by Django 4.1.3 on 2023-06-06 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_questionscore_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionscore',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionscore', to='app.question'),
        ),
    ]
